use_frameworks!

platform :ios, '8.0'

target 'YQTestLogining_Example' do
  pod 'YQTestLogining', :path => '../'

  target 'YQTestLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
